 setwd("/Users/icke/Desktop/tobii-Eyetracker-R")
data <- read.table("tobii-CSVExport-All-Data-noheader-nofilter.tsv",sep="\t", header=TRUE)
# plot(data$GazePointX,data$GazePointY, main="eyetracker", sub="",xlab="X-axis GazePointX", ylab="GazePointY", ylim=c(1024,0), xlim=c(0,1280))
# png(filename="out.png", width = 1280, height = 1024,)
par(bg = 'black')
plot(data$GazePointX,data$GazePointY, sub="", xlab="", ylab="",axes=FALSE, ylim=c(1024,0), xlim=c(0,1280),col="black")
points(data$GazePointX,data$GazePointY, col = "green", cex = .6)
lines(data$GazePointX,data$GazePointY, col = "white")
dev.off()